/*
 * Copyright (C) 2017 oscar
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package FrontEnd;

import BackEnd.*;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author oscar
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public mainMenu mainMenu;
    public ModeloTablaArticulos modelo=new ModeloTablaArticulos();
    private boolean guardar=true;
    
    public Administracion(mainMenu form) {
        mainMenu=form;
        initComponents();
        setLocationRelativeTo(null);
        inicializarColumnas();
        inicializarArbol();
    }
    
    public void inicializarArbol(){
        try {
            //mainMenu.b.root=null;
            String sentenciaSQL="SELECT * FROM ITEMS ";
            Statement statement=mainMenu.b.bd.conexion.createStatement();
            ResultSet resultado=statement.executeQuery(sentenciaSQL);
            
            while(resultado.next()){
                nodoArbol Nodo=new nodoArbol();
                Nodo.setItemID(resultado.getInt(1));
                Nodo.setItemName(resultado.getString(2));
                Nodo.setItemQuant(resultado.getInt(3));
                Nodo.setItemPrice(resultado.getDouble(4));
                
                mainMenu.b.insertar(Nodo.getItemID(), Nodo.getItemName(), Nodo.getItemQuant(), Nodo.getItemPrice(), true);
                this.modelo.articulos.add(Nodo);
            }
            jTable1.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(ArbolDeBusquedaBinaria.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error en inicializacion del ABB", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //ex.printStackTrace();
        }
    }
    
    private void inicializarColumnas(){
        TableColumnModel tColumnModel=new DefaultTableColumnModel();
        
        for(int i=0;i<4;i++){
            TableColumn col=new TableColumn(i);
            
            switch(i){
                case 0:
                    col.setHeaderValue("ID");
                    break;
                case 1:
                    col.setHeaderValue("Nombre");
                    break;
                case 2:
                    col.setHeaderValue("Existencia");
                    break;
                case 3:
                    col.setHeaderValue("Precio");
            }
            tColumnModel.addColumn(col);
        }
        jTable1.setColumnModel(tColumnModel);
    }

    private Administracion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoJtext = new javax.swing.JTextField();
        nombreJtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantidadJtext = new javax.swing.JTextField();
        precioJtext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guardarArt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        eliminarArtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eliminarArtNombre = new javax.swing.JTextField();
        eliminarArt = new javax.swing.JButton();
        buscarArt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        eliminarArtCantidad = new javax.swing.JTextField();
        nuevoArt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de Administracion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setAutoCreateColumnsFromModel(false);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(modelo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 2, 18)); // NOI18N
        jLabel1.setText("Ingreso de Productos");

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 2, 18)); // NOI18N
        jLabel2.setText("Eliminacion de Productos");

        jLabel3.setText("Codigo:");

        codigoJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoJtextActionPerformed(evt);
            }
        });

        nombreJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJtextActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Precio:");

        guardarArt.setText("Guardar");
        guardarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArtActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo:");

        eliminarArtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarArtCodigoKeyPressed(evt);
            }
        });

        jLabel8.setText("Nombre:");

        eliminarArt.setText("Eliminar Articulo");
        eliminarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarArtActionPerformed(evt);
            }
        });

        buscarArt.setText("Buscar");
        buscarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarArtActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad a Eliminar:");

        nuevoArt.setText("Nuevo");
        nuevoArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 82, Short.MAX_VALUE)
                                        .addComponent(buscarArt)
                                        .addGap(69, 69, 69)
                                        .addComponent(eliminarArt)
                                        .addGap(50, 50, 50))
                                    .addComponent(nombreJtext)
                                    .addComponent(eliminarArtNombre)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(codigoJtext)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cantidadJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(eliminarArtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(eliminarArtCantidad)
                                            .addComponent(precioJtext, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(127, 127, 127))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(122, 122, 122)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevoArt)
                        .addGap(18, 18, 18)
                        .addComponent(guardarArt)
                        .addGap(169, 169, 169))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codigoJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cantidadJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarArt)
                            .addComponent(nuevoArt))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(eliminarArtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(eliminarArtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(eliminarArtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarArt)
                            .addComponent(buscarArt)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Articulos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        mainMenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void codigoJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoJtextActionPerformed

    private void nombreJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJtextActionPerformed

    private void guardarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArtActionPerformed
        
        if(mainMenu.b.busqueda(Integer.parseInt(codigoJtext.getText())) && guardar){
            JOptionPane.showMessageDialog(null, "ID ya existe en el sistema, por favor ingrese un ID distinto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if(mainMenu.b.busqueda(Integer.parseInt(codigoJtext.getText())) && !guardar){
            mainMenu.b.aumentarInventario(Integer.parseInt(codigoJtext.getText()), Integer.parseInt(cantidadJtext.getText()));
            //inicializarArbol();
            JOptionPane.showMessageDialog(null,"Item Actualizado");
            codigoJtext.setText("");
            nombreJtext.setText("");
            cantidadJtext.setText("");
            precioJtext.setText("");
        }else{
            if(mainMenu.b.insertar(Integer.parseInt(codigoJtext.getText()), nombreJtext.getText(), Integer.parseInt(cantidadJtext.getText()), Double.parseDouble(precioJtext.getText()))){
                //inicializarArbol();
                JOptionPane.showMessageDialog(null,"Item Agregado");
                codigoJtext.setText("");
                nombreJtext.setText("");
                cantidadJtext.setText("");
                precioJtext.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error al agregar item","Advertencia",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_guardarArtActionPerformed

    private void eliminarArtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarArtCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            nodoArbol nodo;
            if(mainMenu.b.busqueda(Integer.parseInt(eliminarArtCodigo.getText()))){
                nodo=mainMenu.b.auxNode;
                eliminarArtNombre.setText(nodo.getItemName());
                eliminarArtCantidad.setText(nodo.getItemQuant().toString());
            }else{
                JOptionPane.showMessageDialog(null, "No se encontro el articulo");
            }
        }
    }//GEN-LAST:event_eliminarArtCodigoKeyPressed

    private void buscarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarArtActionPerformed
        nodoArbol nodo;
        if(mainMenu.b.busqueda(Integer.parseInt(eliminarArtCodigo.getText()))){
            nodo=mainMenu.b.auxNode;
            eliminarArtNombre.setText(nodo.getItemName());
            eliminarArtCantidad.setText(nodo.getItemQuant().toString());
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro el articulo");
        }
    }//GEN-LAST:event_buscarArtActionPerformed

    private void eliminarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarArtActionPerformed
        nodoArbol nodo;
        mainMenu.b.busqueda(Integer.parseInt(eliminarArtCodigo.getText()));
        nodo=mainMenu.b.auxNode;
        int respuesta=JOptionPane.showConfirmDialog(null, "¿Desea eliminar "+eliminarArtCantidad.getText()+" articulos del tipo "+eliminarArtNombre.getText()+"?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_OPTION){
            if(Objects.equals(Integer.parseInt(eliminarArtCantidad.getText()), nodo.getItemQuant())){
                mainMenu.b.eliminar(Integer.parseInt(eliminarArtCodigo.getText()));
                JOptionPane.showMessageDialog(null, "Eliminado Completamente");
            }else{
                
                System.out.print("\nSe elimina externo");
                mainMenu.b.reducirInventario(Integer.parseInt(eliminarArtCodigo.getText()),Integer.parseInt(eliminarArtCantidad.getText()));
            }
        }
    }//GEN-LAST:event_eliminarArtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int clicks = evt.getClickCount();
        int row = jTable1.rowAtPoint(evt.getPoint());
        
        if(clicks==2){
            nodoArbol nodo=modelo.articulos.get(row);
            
            codigoJtext.setText(nodo.getItemID().toString());
            eliminarArtCodigo.setText(nodo.getItemID().toString());
            nombreJtext.setText(nodo.getItemName());
            eliminarArtNombre.setText(nodo.getItemName());
            cantidadJtext.setText(nodo.getItemQuant().toString());
            eliminarArtCantidad.setText(nodo.getItemQuant().toString());
            precioJtext.setText(String.valueOf(nodo.getItemPrice()));
            guardar=false;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void nuevoArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArtActionPerformed
        codigoJtext.setText("");
        guardar=true;
    }//GEN-LAST:event_nuevoArtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarArt;
    private javax.swing.JTextField cantidadJtext;
    private javax.swing.JTextField codigoJtext;
    private javax.swing.JButton eliminarArt;
    private javax.swing.JTextField eliminarArtCantidad;
    private javax.swing.JTextField eliminarArtCodigo;
    private javax.swing.JTextField eliminarArtNombre;
    private javax.swing.JButton guardarArt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreJtext;
    private javax.swing.JButton nuevoArt;
    private javax.swing.JTextField precioJtext;
    // End of variables declaration//GEN-END:variables
}
